/**
 * Contains support for GWT services inside a normal gluewine context.
 * <p>
 * The GWT servlets will not run in the war file (although a war file will
 * likely exist for the client-side assets).
 * </p>
 * <p>
 * Note that the *.gwt.rpc files generated by the gwt build need to be copied to lib/gwt-rpc/.
 * </p>
 * <p>
 * Also, the servlets will likely not run at exactly the path the gwt compiler expects them,
 * so the client code needs to have:
 * </p>
 * <br>
 * <code>
 *          ((ServiceDefTarget) myService).setServiceEntryPoint("/myServicerPath/");
 * </code>
 * <p>
 * See {@link org.gluewine.gwt} for gwt support in a more traditional way.
 * </p>
 */
package org.gluewine.gluedgwt;
